spring:
  data:
    redis:
      repositories:
        enabled: false

---
spring:
  config:
    activate:
      on-profile:
        - local

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000
      lettuce:
        pool:
          max-active: 3
          max-idle: 3
          min-idle: 1
      key-prefix: myw
      cluster-on: false
      command-timeout: 2000
