spring:
  jpa:
    admin:
      show-sql: true
      hibernate:
          ddl-auto: update

  datasource:
    admin:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/myw_admin?serverTimezone=UTC
        username: root
        password: andyxtreedb
        pool-name: HikariAdminPool
        maximum-pool-size: 2
