spring:
  jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
      properties:
        '[hibernate.format_sql]': true
        '[hibernate.enable_lazy_load_no_trans]': true

---
spring:
  config:
    activate:
      on-profile:
        - local
    driverClassName: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
